backend:
  name: github
  repo: YA-Menu/Test-3  # اكتب هني اسم حسابك في جيت هب واسم المستودع مالك
  branch: main                  # اسم البرانش الأساسي مالك (غالباً main)

media_folder: "images"
public_folder: "images"

collections:
  - name: "menu"
    label: "إدارة المنيو"
    files:
      - file: "menu-data.json"
        name: "menu_items"
        label: "قائمة الأطباق"
        fields:
          - name: items
            label: الأطباق
            widget: list
            fields:
              - {label: "اسم الطبق", name: "title", widget: "string"}
              - {label: "الوصف", name: "description", widget: "string", required: false}
              - {label: "السعر", name: "price", widget: "string"}
              - {label: "الصورة", name: "image", widget: "image"}
